library(jupyter.widgets.generate) # >= 0.0.0.9013
library(purrr)
library(tibble)

# Style widgets -----------------------------------------------------------
generated_style_file <- file("R/generated-Style.R", open = "w")
styles <- c(
  "SliderStyle", "ButtonStyle", "CheckboxStyle", "TextStyle", "HTMLStyle",
  "HTMLMathStyle", "LabelStyle", "ProgressStyle", "ToggleButtonStyle"
  # "ToggleButtonsStyle"
)
writeLines(con = generated_style_file, c(
  "# Generated by wiipoc/data-raw/generated.R: do not edit by hand",
  ""
))
purrr::walk(styles, \(style) {
  writeLines(con = generated_style_file, c(
    generate_style_widget(style),
    ""
  ))
})
close(generated_style_file)


# DOM Widgets -------------------------------------------------------------
dom <- tribble(
  ~names             , ~styles            , ~formals ,

  "Accordion"        , NULL               , c("children"),
  "Checkbox"         , "CheckboxStyle"    , c("value"),
  "ColorPicker"      , NULL               , c("value"),
  "ColorsInput"      , NULL               , c("value", "description", "description_allow_html", "placeholder"),
  "Combobox"         , NULL               , c("value"),
  "DatePicker"       , NULL               , c("value", "min", "max", "step"),
  "Datetime"         , NULL               , c("value", "min", "max"),
  "NaiveDatetime"    , NULL               , c("value", "min", "max"),
  "IntSlider"        , "SliderStyle"      , c("value", "min", "max", "step"),
  "FloatSlider"      , "SliderStyle"      , c("value", "min", "max", "step"),
  "FloatLogSlider"   , "SliderStyle"      , c("value", "min", "max", "step"),
  "FloatRangeSlider" , "SliderStyle"      , c("value", "min", "max", "step"),
  "IntRangeSlider"   , "SliderStyle"      , c("value", "min", "max", "step"),
  "Text"             , "TextStyle"        , c("value", "placeholder"),
  "IntText"          , "TextStyle"        , c("value", "step"),
  "FloatText"        , "TextStyle"        , c("value", "step"),
  "BoundedIntText"   , "TextStyle"        , c("value", "min", "max", "step"),
  "BoundedFloatText" , "TextStyle"        , c("value", "min", "max", "step"),
  "HTML"             , "HTMLStyle"        , c("value", "placeholder"),
  "HTMLMath"         , "HTMLMathStyle"    , c("value", "placeholder"),
  "ToggleButton"     , "ToggleButtonStyle", c("value"),
  "Label"            , "LabelStyle"       , c("value", "placeholder"),
  "IntProgress"      , "ProgressStyle"    , c("value", "min", "max"),
  "FloatProgress"    , "ProgressStyle"    , c("value", "min", "max"),
  "Password"         , NULL               , c("value"),
  "Box"              , NULL               , c("children"),
  "HBox"             , NULL               , c("children"),
  "VBox"             , NULL               , c("children"),
  "GridBox"          , NULL               , c("children"),
  "Tab"              , NULL               , c("children"),
  "Stack"            , NULL               , c("children"),
  "Button"           , "ButtonStyle"      , c("description"),
  "Textarea"         , NULL               , c("value", "rows", "placeholder"),
  "Time"             , NULL               , c("value", "min", "max", "step"),
  "Select"           , NULL               , c("options", "index")
)

generated_dom_file <- file("R/generated-DOM.R", open = "w")
writeLines(con = generated_dom_file, c(
  "# Generated by wiipoc/data-raw/generated.R: do not edit by hand",
  ""
))
with(dom, purrr::pwalk(list(names, styles, formals), \(name, style, formal) {
  writeLines(con = generated_dom_file, c(
    generate_dom_widget(name, style = style[[1]], formals = formal),
    ''
  ))
}))
close(generated_dom_file)

# TODO:
# Link
# DirectionalLink

# TODO: update jupyter.widgets.generate to handle _options_label
#       https://github.com/romainfrancois/jupyter.widgets.generate/issues/7
# writeLines(generate_dom_widget("ToggleButtons", style = "ToggleButtonsStyle"), "R/generated-ToggleButtons.R")

# Audio
# Dropdown
# ControllerAxis
# ControllerButton
# Controller
# FileUpload
# FloatsInput
# Image
# IntsInput
# Play
# RadioButton
# SelectMultiple
# SelectionRangeSlider
# SelectionSlider
# TagsInput
# ToggleButtons
# Valid
# Video
# Output

# ToggleButtonsStyle

