library(jupyter.widgets.generate) # >= 0.0.0.9009
library(purrr)
library(tibble)

# Style widgets -----------------------------------------------------------
generated_style_file <- file("R/generated-Style.R", open = "w")
styles <- c(
  "SliderStyle", "ButtonStyle", "CheckboxStyle", "TextStyle", "HTMLStyle",
  "HTMLMathStyle", "LabelStyle", "ProgressStyle", "ToggleButtonStyle"
  # "ToggleButtonsStyle"
)
writeLines(con = generated_style_file, c(
  "# Generated by wiipoc/data-raw/generated.R: do not edit by hand",
  ""
))
purrr::walk(styles, \(style) writeLines(generate_style_widget(style), con = generated_style_file))
close(generated_style_file)


# DOM Widgets -------------------------------------------------------------
dom <- tribble(
  ~names             , ~styles,

  "Accordion"        , NULL,
  "Checkbox"         , "CheckboxStyle",
  "ColorPicker"      , NULL,
  "ColorsInput"      , NULL,
  "Combobox"         , NULL,
  "DatePicker"       , NULL,
  "Datetime"         , NULL,
  "NaiveDatetime"    , NULL,
  "IntSlider"        , "SliderStyle",
  "FloatSlider"      , "SliderStyle",
  "FloatLogSlider"   , "SliderStyle",
  "FloatRangeSlider" , "SliderStyle",
  "IntRangeSlider"   , "SliderStyle",
  "Text"             , "TextStyle",
  "IntText"          , "TextStyle",
  "FloatText"        , "TextStyle",
  "BoundedIntText"   , "TextStyle",
  "BoundedFloatText" , "TextStyle",
  "HTML"             , "HTMLStyle",
  "HTMLMath"         , "HTMLMathStyle",
  "ToggleButton"     , "ToggleButtonStyle",
  "Label"            , "LabelStyle",
  "IntProgress"      , "ProgressStyle",
  "FloatProgress"    , "ProgressStyle",
  "Password"         , NULL,
  "Box"              , NULL,
  "HBox"             , NULL,
  "VBox"             , NULL,
  "GridBox"          , NULL,
  "Tab"              , NULL,
  "Stack"            , NULL,
  "Button"           , "ButtonStyle",
  "Textarea"         , NULL,
  "Time"             , NULL
)

generated_dom_file <- file("R/generated-DOM.R", open = "w")
writeLines(con = generated_dom_file, c(
  "# Generated by wiipoc/data-raw/generated.R: do not edit by hand",
  ""
))
with(dom, purrr::walk2(names, styles, \(name, style) {
  writeLines(con = generated_dom_file, c(
    generate_dom_widget(name, style = style[[1]]),
    ''
  ))
}))
close(generated_dom_file)

# TODO:
# Link
# DirectionalLink

# TODO: update jupyter.widgets.generate to handle _options_label
#       https://github.com/romainfrancois/jupyter.widgets.generate/issues/7
# writeLines(generate_dom_widget("ToggleButtons", style = "ToggleButtonsStyle"), "R/generated-ToggleButtons.R")

# Audio
# Dropdown
# ControllerAxis
# ControllerButton
# Controller
# FileUpload
# FloatsInput
# Image
# IntsInput
# Play
# RadioButton
# Select
# SelectMultiple
# SelectionRangeSlider
# SelectionSlider
# TagsInput
# ToggleButtons
# Valid
# Video
# Output

# ToggleButtonsStyle

