# Generated by jupyter.widgets.generate::generate_dom_widget("ToggleButton"): do not edit by hand

#' ToggleButton widget
#'
#' @export
jupyter.widget.ToggleButton <- R6::R6Class("jupyter.widget.ToggleButton", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param button_style Use a predefined styling for the button.
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes.
    #' @param icon Font-awesome icon.
    #' @param value Bool value
    #' @param style Must inherit from [jupyter.widget.ToggleButtonStyle].
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ToggleButton' widget
    initialize = function(
      button_style = "",
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      icon = "",
      value = FALSE,
      style = ToggleButtonStyle(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        button_style = self$check_state('button_style', button_style),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        icon = self$check_state('icon', icon),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ToggleButtonModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "ToggleButtonView",
        style = style, 
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field button_style
    #' Use a predefined styling for the button.
    button_style = function(x) if(missing(x)) private$state_[['button_style']] else self$update(button_style = self$check_state('button_style', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes.
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field icon
    #' Font-awesome icon.
    icon = function(x) if(missing(x)) private$state_[['icon']] else self$update(icon = self$check_state('icon', x)),
    
    #' @field value
    #' Bool value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' ToggleButton widget
#'
#' @param button_style Use a predefined styling for the button.
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes.
#' @param icon Font-awesome icon.
#' @param value Bool value
#' 
#' @param style Must inherit from [jupyter.widget.ToggleButtonStyle].
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ToggleButton <- function(
  button_style = "",
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  icon = "",
  value = FALSE,
  style = ToggleButtonStyle(),
  ...,
  error_call = current_env()
){
  jupyter.widget.ToggleButton$new(
    button_style = button_style,
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    icon = icon,
    value = value,
    style = style,
    ...,
    error_call = error_call
  )
}

rlang::on_load({
  set_widget_state_check("jupyter.widget.ToggleButton", "button_style", unbox_one_of(c("primary", "success", "info", "warning", "danger"), allow_null = TRUE, allow_empty = TRUE))
})
