# Generated by jupyter.widgets.generate::generate_dom_widget("BoundedIntText"): do not edit by hand

#' BoundedIntText widget
#'
#' @export
jupyter.widget.BoundedIntText <- R6::R6Class("jupyter.widget.BoundedIntText", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param continuous_update Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes
    #' @param max Max value
    #' @param min Min value
    #' @param step Minimum step to increment the value
    #' @param value Int value
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.BoundedIntText' widget
    initialize = function(
      continuous_update = FALSE,
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      max = 100L,
      min = 0L,
      step = 1L,
      value = 0L,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        continuous_update = self$check_state('continuous_update', continuous_update),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        max = self$check_state('max', max),
        min = self$check_state('min', min),
        step = self$check_state('step', step),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "BoundedIntTextModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "IntTextView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field continuous_update
    #' Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
    continuous_update = function(x) if(missing(x)) private$state_[['continuous_update']] else self$update(continuous_update = self$check_state('continuous_update', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field max
    #' Max value
    max = function(x) if(missing(x)) private$state_[['max']] else self$update(max = self$check_state('max', x)),
    
    #' @field min
    #' Min value
    min = function(x) if(missing(x)) private$state_[['min']] else self$update(min = self$check_state('min', x)),
    
    #' @field step
    #' Minimum step to increment the value
    step = function(x) if(missing(x)) private$state_[['step']] else self$update(step = self$check_state('step', x)),
    
    #' @field value
    #' Int value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' BoundedIntText widget
#'
#' @param continuous_update Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes
#' @param max Max value
#' @param min Min value
#' @param step Minimum step to increment the value
#' @param value Int value
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
BoundedIntText <- function(
  continuous_update = FALSE,
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  max = 100L,
  min = 0L,
  step = 1L,
  value = 0L,
  ...,
  error_call = current_env()
){
  jupyter.widget.BoundedIntText$new(
    continuous_update = continuous_update,
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    max = max,
    min = min,
    step = step,
    value = value,
    ...,
    error_call = error_call
  )
}
