# Generated by jupyter.widgets.generate::generate_dom_widget("ColorsInput"): do not edit by hand

#' ColorsInput widget
#'
#' @export
jupyter.widget.ColorsInput <- R6::R6Class("jupyter.widget.ColorsInput", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param allow_duplicates (undocumented)
    #' @param allowed_tags (undocumented)
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param placeholder (undocumented)
    #' @param value List of string tags
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ColorsInput' widget
    initialize = function(
      allow_duplicates = TRUE,
      allowed_tags = list(),
      description = "",
      description_allow_html = FALSE,
      placeholder = "\U{200B}",
      value = list(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        allow_duplicates = self$check_state('allow_duplicates', allow_duplicates),
        allowed_tags = self$check_state('allowed_tags', allowed_tags),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        placeholder = self$check_state('placeholder', placeholder),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ColorsInputModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "ColorsInputView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field allow_duplicates
    #' 
    allow_duplicates = function(x) if(missing(x)) private$state_[['allow_duplicates']] else self$update(allow_duplicates = self$check_state('allow_duplicates', x)),
    
    #' @field allowed_tags
    #' 
    allowed_tags = function(x) if(missing(x)) private$state_[['allowed_tags']] else self$update(allowed_tags = self$check_state('allowed_tags', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field placeholder
    #' 
    placeholder = function(x) if(missing(x)) private$state_[['placeholder']] else self$update(placeholder = self$check_state('placeholder', x)),
    
    #' @field value
    #' List of string tags
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' ColorsInput widget
#'
#' @param allow_duplicates (undocumented)
#' @param allowed_tags (undocumented)
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param placeholder (undocumented)
#' @param value List of string tags
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ColorsInput <- function(
  allow_duplicates = TRUE,
  allowed_tags = list(),
  description = "",
  description_allow_html = FALSE,
  placeholder = "\U{200B}",
  value = list(),
  ...,
  error_call = current_env()
){
  jupyter.widget.ColorsInput$new(
    allow_duplicates = allow_duplicates,
    allowed_tags = allowed_tags,
    description = description,
    description_allow_html = description_allow_html,
    placeholder = placeholder,
    value = value,
    ...,
    error_call = error_call
  )
}

