# Generated by jupyter.widgets.generate::generate_style_widget("ButtonStyle"): do not edit by hand

#' ButtonStyle widget
#'
#' @export
jupyter.widget.ButtonStyle <- R6::R6Class("jupyter.widget.ButtonStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param button_color Color of the button
    #' @param font_family Button text font family.
    #' @param font_size Button text font size.
    #' @param font_style Button text font style.
    #' @param font_variant Button text font variant.
    #' @param font_weight Button text font weight.
    #' @param text_color Button text color.
    #' @param text_decoration Button text decoration.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ButtonStyle' widget
    initialize = function(
      button_color = NULL,
      font_family = NULL,
      font_size = NULL,
      font_style = NULL,
      font_variant = NULL,
      font_weight = NULL,
      text_color = NULL,
      text_decoration = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        button_color = self$check_state('button_color', button_color),
        font_family = self$check_state('font_family', font_family),
        font_size = self$check_state('font_size', font_size),
        font_style = self$check_state('font_style', font_style),
        font_variant = self$check_state('font_variant', font_variant),
        font_weight = self$check_state('font_weight', font_weight),
        text_color = self$check_state('text_color', text_color),
        text_decoration = self$check_state('text_decoration', text_decoration)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ButtonStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field button_color
    #' Color of the button
    button_color = function(x) if(missing(x)) private$state_[['button_color']] else self$update(button_color = self$check_state('button_color', x)),
    
    #' @field font_family
    #' Button text font family.
    font_family = function(x) if(missing(x)) private$state_[['font_family']] else self$update(font_family = self$check_state('font_family', x)),
    
    #' @field font_size
    #' Button text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field font_style
    #' Button text font style.
    font_style = function(x) if(missing(x)) private$state_[['font_style']] else self$update(font_style = self$check_state('font_style', x)),
    
    #' @field font_variant
    #' Button text font variant.
    font_variant = function(x) if(missing(x)) private$state_[['font_variant']] else self$update(font_variant = self$check_state('font_variant', x)),
    
    #' @field font_weight
    #' Button text font weight.
    font_weight = function(x) if(missing(x)) private$state_[['font_weight']] else self$update(font_weight = self$check_state('font_weight', x)),
    
    #' @field text_color
    #' Button text color.
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x)),
    
    #' @field text_decoration
    #' Button text decoration.
    text_decoration = function(x) if(missing(x)) private$state_[['text_decoration']] else self$update(text_decoration = self$check_state('text_decoration', x))
  )
)

#' ButtonStyle widget
#'
#' @param button_color Color of the button
#' @param font_family Button text font family.
#' @param font_size Button text font size.
#' @param font_style Button text font style.
#' @param font_variant Button text font variant.
#' @param font_weight Button text font weight.
#' @param text_color Button text color.
#' @param text_decoration Button text decoration.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ButtonStyle <- function(
  button_color = NULL,
  font_family = NULL,
  font_size = NULL,
  font_style = NULL,
  font_variant = NULL,
  font_weight = NULL,
  text_color = NULL,
  text_decoration = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.ButtonStyle$new(
    button_color = button_color,
    font_family = font_family,
    font_size = font_size,
    font_style = font_style,
    font_variant = font_variant,
    font_weight = font_weight,
    text_color = text_color,
    text_decoration = text_decoration,
    ...,
    error_call = error_call
  )
}
