# Generated by jupyter.widgets.generate::generate_dom_widget("FloatProgress"): do not edit by hand

#' FloatProgress widget
#'
#' @export
jupyter.widget.FloatProgress <- R6::R6Class("jupyter.widget.FloatProgress", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param bar_style Use a predefined styling for the progress bar.
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param max Max value
    #' @param min Min value
    #' @param orientation Vertical or horizontal.
    #' @param value Float value
    #' @param style Must inherit from [jupyter.widget.ProgressStyle].
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.FloatProgress' widget
    initialize = function(
      bar_style = "",
      description = "",
      description_allow_html = FALSE,
      max = 100,
      min = 0,
      orientation = "horizontal",
      value = 0,
      style = ProgressStyle(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        bar_style = self$check_state('bar_style', bar_style),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        max = self$check_state('max', max),
        min = self$check_state('min', min),
        orientation = self$check_state('orientation', orientation),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "FloatProgressModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "ProgressView",
        style = style, 
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field bar_style
    #' Use a predefined styling for the progress bar.
    bar_style = function(x) if(missing(x)) private$state_[['bar_style']] else self$update(bar_style = self$check_state('bar_style', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field max
    #' Max value
    max = function(x) if(missing(x)) private$state_[['max']] else self$update(max = self$check_state('max', x)),
    
    #' @field min
    #' Min value
    min = function(x) if(missing(x)) private$state_[['min']] else self$update(min = self$check_state('min', x)),
    
    #' @field orientation
    #' Vertical or horizontal.
    orientation = function(x) if(missing(x)) private$state_[['orientation']] else self$update(orientation = self$check_state('orientation', x)),
    
    #' @field value
    #' Float value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' FloatProgress widget
#'
#' @param bar_style Use a predefined styling for the progress bar.
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param max Max value
#' @param min Min value
#' @param orientation Vertical or horizontal.
#' @param value Float value
#' 
#' @param style Must inherit from [jupyter.widget.ProgressStyle].
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
FloatProgress <- function(
  bar_style = "",
  description = "",
  description_allow_html = FALSE,
  max = 100,
  min = 0,
  orientation = "horizontal",
  value = 0,
  style = ProgressStyle(),
  ...,
  error_call = current_env()
){
  jupyter.widget.FloatProgress$new(
    bar_style = bar_style,
    description = description,
    description_allow_html = description_allow_html,
    max = max,
    min = min,
    orientation = orientation,
    value = value,
    style = style,
    ...,
    error_call = error_call
  )
}
