# Generated by jupyter.widgets.generate::generate_dom_widget("DatePicker"): do not edit by hand

#' DatePicker widget
#'
#' @export
jupyter.widget.DatePicker <- R6::R6Class("jupyter.widget.DatePicker", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes.
    #' @param max (undocumented)
    #' @param min (undocumented)
    #' @param step The date step to use for the picker, in days, or "any".
    #' @param value (undocumented)
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.DatePicker' widget
    initialize = function(
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      max = NULL,
      min = NULL,
      step = 1L,
      value = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        max = self$check_state('max', max),
        min = self$check_state('min', min),
        step = self$check_state('step', step),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "DatePickerModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "DatePickerView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes.
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field max
    #' 
    max = function(x) if(missing(x)) private$state_[['max']] else self$update(max = self$check_state('max', x)),
    
    #' @field min
    #' 
    min = function(x) if(missing(x)) private$state_[['min']] else self$update(min = self$check_state('min', x)),
    
    #' @field step
    #' The date step to use for the picker, in days, or "any".
    step = function(x) if(missing(x)) private$state_[['step']] else self$update(step = self$check_state('step', x)),
    
    #' @field value
    #' 
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' DatePicker widget
#'
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes.
#' @param max (undocumented)
#' @param min (undocumented)
#' @param step The date step to use for the picker, in days, or "any".
#' @param value (undocumented)
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
DatePicker <- function(
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  max = NULL,
  min = NULL,
  step = 1L,
  value = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.DatePicker$new(
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    max = max,
    min = min,
    step = step,
    value = value,
    ...,
    error_call = error_call
  )
}
