# Generated by jupyter.widgets.generate::generate_style_widget("ProgressStyle"): do not edit by hand

#' ProgressStyle widget
#'
#' @export
jupyter.widget.ProgressStyle <- R6::R6Class("jupyter.widget.ProgressStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param bar_color Color of the progress bar.
    #' @param description_width Width of the description to the side of the control.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ProgressStyle' widget
    initialize = function(
      bar_color = NULL,
      description_width = "",

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        bar_color = self$check_state('bar_color', bar_color),
        description_width = self$check_state('description_width', description_width)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ProgressStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field bar_color
    #' Color of the progress bar.
    bar_color = function(x) if(missing(x)) private$state_[['bar_color']] else self$update(bar_color = self$check_state('bar_color', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x))
  )
)

#' ProgressStyle widget
#'
#' @param bar_color Color of the progress bar.
#' @param description_width Width of the description to the side of the control.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ProgressStyle <- function(
  bar_color = NULL,
  description_width = "",
  ...,
  error_call = current_env()
){
  jupyter.widget.ProgressStyle$new(
    bar_color = bar_color,
    description_width = description_width,
    ...,
    error_call = error_call
  )
}
