# Generated by wiipoc/data-raw/generated.R: do not edit by hand

#' SliderStyle widget
#'
#' @export
jupyter.widget.SliderStyle <- R6::R6Class("jupyter.widget.SliderStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param description_width Width of the description to the side of the control.
    #' @param handle_color Color of the slider handle.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.SliderStyle' widget
    initialize = function(
      description_width = "",
      handle_color = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        description_width = self$check_state('description_width', description_width),
        handle_color = self$check_state('handle_color', handle_color)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "SliderStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field handle_color
    #' Color of the slider handle.
    handle_color = function(x) if(missing(x)) private$state_[['handle_color']] else self$update(handle_color = self$check_state('handle_color', x))
  )
)

#' SliderStyle widget
#'
#' @param description_width Width of the description to the side of the control.
#' @param handle_color Color of the slider handle.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
SliderStyle <- function(
  description_width = "",
  handle_color = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.SliderStyle$new(
    description_width = description_width,
    handle_color = handle_color,
    ...,
    error_call = error_call
  )
}

#' ButtonStyle widget
#'
#' @export
jupyter.widget.ButtonStyle <- R6::R6Class("jupyter.widget.ButtonStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param button_color Color of the button
    #' @param font_family Button text font family.
    #' @param font_size Button text font size.
    #' @param font_style Button text font style.
    #' @param font_variant Button text font variant.
    #' @param font_weight Button text font weight.
    #' @param text_color Button text color.
    #' @param text_decoration Button text decoration.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ButtonStyle' widget
    initialize = function(
      button_color = NULL,
      font_family = NULL,
      font_size = NULL,
      font_style = NULL,
      font_variant = NULL,
      font_weight = NULL,
      text_color = NULL,
      text_decoration = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        button_color = self$check_state('button_color', button_color),
        font_family = self$check_state('font_family', font_family),
        font_size = self$check_state('font_size', font_size),
        font_style = self$check_state('font_style', font_style),
        font_variant = self$check_state('font_variant', font_variant),
        font_weight = self$check_state('font_weight', font_weight),
        text_color = self$check_state('text_color', text_color),
        text_decoration = self$check_state('text_decoration', text_decoration)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ButtonStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field button_color
    #' Color of the button
    button_color = function(x) if(missing(x)) private$state_[['button_color']] else self$update(button_color = self$check_state('button_color', x)),
    
    #' @field font_family
    #' Button text font family.
    font_family = function(x) if(missing(x)) private$state_[['font_family']] else self$update(font_family = self$check_state('font_family', x)),
    
    #' @field font_size
    #' Button text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field font_style
    #' Button text font style.
    font_style = function(x) if(missing(x)) private$state_[['font_style']] else self$update(font_style = self$check_state('font_style', x)),
    
    #' @field font_variant
    #' Button text font variant.
    font_variant = function(x) if(missing(x)) private$state_[['font_variant']] else self$update(font_variant = self$check_state('font_variant', x)),
    
    #' @field font_weight
    #' Button text font weight.
    font_weight = function(x) if(missing(x)) private$state_[['font_weight']] else self$update(font_weight = self$check_state('font_weight', x)),
    
    #' @field text_color
    #' Button text color.
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x)),
    
    #' @field text_decoration
    #' Button text decoration.
    text_decoration = function(x) if(missing(x)) private$state_[['text_decoration']] else self$update(text_decoration = self$check_state('text_decoration', x))
  )
)

#' ButtonStyle widget
#'
#' @param button_color Color of the button
#' @param font_family Button text font family.
#' @param font_size Button text font size.
#' @param font_style Button text font style.
#' @param font_variant Button text font variant.
#' @param font_weight Button text font weight.
#' @param text_color Button text color.
#' @param text_decoration Button text decoration.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ButtonStyle <- function(
  button_color = NULL,
  font_family = NULL,
  font_size = NULL,
  font_style = NULL,
  font_variant = NULL,
  font_weight = NULL,
  text_color = NULL,
  text_decoration = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.ButtonStyle$new(
    button_color = button_color,
    font_family = font_family,
    font_size = font_size,
    font_style = font_style,
    font_variant = font_variant,
    font_weight = font_weight,
    text_color = text_color,
    text_decoration = text_decoration,
    ...,
    error_call = error_call
  )
}

rlang::on_load({
  set_widget_state_check("jupyter.widget.ButtonStyle", "font_variant", unbox_one_of(c("normal", "small-caps", "all-small-caps", "petite-caps", "all-petite-caps", "unicase", "titling-caps"), allow_null = TRUE, allow_empty = FALSE))
})
#' CheckboxStyle widget
#'
#' @export
jupyter.widget.CheckboxStyle <- R6::R6Class("jupyter.widget.CheckboxStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.CheckboxStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "CheckboxStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x))
  )
)

#' CheckboxStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
CheckboxStyle <- function(
  background = NULL,
  description_width = "",
  ...,
  error_call = current_env()
){
  jupyter.widget.CheckboxStyle$new(
    background = background,
    description_width = description_width,
    ...,
    error_call = error_call
  )
}

#' TextStyle widget
#'
#' @export
jupyter.widget.TextStyle <- R6::R6Class("jupyter.widget.TextStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #' @param font_size Text font size.
    #' @param text_color Text color
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.TextStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",
      font_size = NULL,
      text_color = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width),
        font_size = self$check_state('font_size', font_size),
        text_color = self$check_state('text_color', text_color)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "TextStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field font_size
    #' Text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field text_color
    #' Text color
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x))
  )
)

#' TextStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' @param font_size Text font size.
#' @param text_color Text color
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
TextStyle <- function(
  background = NULL,
  description_width = "",
  font_size = NULL,
  text_color = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.TextStyle$new(
    background = background,
    description_width = description_width,
    font_size = font_size,
    text_color = text_color,
    ...,
    error_call = error_call
  )
}

#' HTMLStyle widget
#'
#' @export
jupyter.widget.HTMLStyle <- R6::R6Class("jupyter.widget.HTMLStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #' @param font_size Text font size.
    #' @param text_color Text color
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.HTMLStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",
      font_size = NULL,
      text_color = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width),
        font_size = self$check_state('font_size', font_size),
        text_color = self$check_state('text_color', text_color)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "HTMLStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field font_size
    #' Text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field text_color
    #' Text color
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x))
  )
)

#' HTMLStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' @param font_size Text font size.
#' @param text_color Text color
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
HTMLStyle <- function(
  background = NULL,
  description_width = "",
  font_size = NULL,
  text_color = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.HTMLStyle$new(
    background = background,
    description_width = description_width,
    font_size = font_size,
    text_color = text_color,
    ...,
    error_call = error_call
  )
}

#' HTMLMathStyle widget
#'
#' @export
jupyter.widget.HTMLMathStyle <- R6::R6Class("jupyter.widget.HTMLMathStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #' @param font_size Text font size.
    #' @param text_color Text color
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.HTMLMathStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",
      font_size = NULL,
      text_color = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width),
        font_size = self$check_state('font_size', font_size),
        text_color = self$check_state('text_color', text_color)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "HTMLMathStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field font_size
    #' Text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field text_color
    #' Text color
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x))
  )
)

#' HTMLMathStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' @param font_size Text font size.
#' @param text_color Text color
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
HTMLMathStyle <- function(
  background = NULL,
  description_width = "",
  font_size = NULL,
  text_color = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.HTMLMathStyle$new(
    background = background,
    description_width = description_width,
    font_size = font_size,
    text_color = text_color,
    ...,
    error_call = error_call
  )
}

#' LabelStyle widget
#'
#' @export
jupyter.widget.LabelStyle <- R6::R6Class("jupyter.widget.LabelStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #' @param font_family Label text font family.
    #' @param font_size Text font size.
    #' @param font_style Label text font style.
    #' @param font_variant Label text font variant.
    #' @param font_weight Label text font weight.
    #' @param text_color Text color
    #' @param text_decoration Label text decoration.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.LabelStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",
      font_family = NULL,
      font_size = NULL,
      font_style = NULL,
      font_variant = NULL,
      font_weight = NULL,
      text_color = NULL,
      text_decoration = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width),
        font_family = self$check_state('font_family', font_family),
        font_size = self$check_state('font_size', font_size),
        font_style = self$check_state('font_style', font_style),
        font_variant = self$check_state('font_variant', font_variant),
        font_weight = self$check_state('font_weight', font_weight),
        text_color = self$check_state('text_color', text_color),
        text_decoration = self$check_state('text_decoration', text_decoration)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "LabelStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field font_family
    #' Label text font family.
    font_family = function(x) if(missing(x)) private$state_[['font_family']] else self$update(font_family = self$check_state('font_family', x)),
    
    #' @field font_size
    #' Text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field font_style
    #' Label text font style.
    font_style = function(x) if(missing(x)) private$state_[['font_style']] else self$update(font_style = self$check_state('font_style', x)),
    
    #' @field font_variant
    #' Label text font variant.
    font_variant = function(x) if(missing(x)) private$state_[['font_variant']] else self$update(font_variant = self$check_state('font_variant', x)),
    
    #' @field font_weight
    #' Label text font weight.
    font_weight = function(x) if(missing(x)) private$state_[['font_weight']] else self$update(font_weight = self$check_state('font_weight', x)),
    
    #' @field text_color
    #' Text color
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x)),
    
    #' @field text_decoration
    #' Label text decoration.
    text_decoration = function(x) if(missing(x)) private$state_[['text_decoration']] else self$update(text_decoration = self$check_state('text_decoration', x))
  )
)

#' LabelStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' @param font_family Label text font family.
#' @param font_size Text font size.
#' @param font_style Label text font style.
#' @param font_variant Label text font variant.
#' @param font_weight Label text font weight.
#' @param text_color Text color
#' @param text_decoration Label text decoration.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
LabelStyle <- function(
  background = NULL,
  description_width = "",
  font_family = NULL,
  font_size = NULL,
  font_style = NULL,
  font_variant = NULL,
  font_weight = NULL,
  text_color = NULL,
  text_decoration = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.LabelStyle$new(
    background = background,
    description_width = description_width,
    font_family = font_family,
    font_size = font_size,
    font_style = font_style,
    font_variant = font_variant,
    font_weight = font_weight,
    text_color = text_color,
    text_decoration = text_decoration,
    ...,
    error_call = error_call
  )
}

rlang::on_load({
  set_widget_state_check("jupyter.widget.LabelStyle", "font_variant", unbox_one_of(c("normal", "small-caps", "all-small-caps", "petite-caps", "all-petite-caps", "unicase", "titling-caps"), allow_null = TRUE, allow_empty = FALSE))
})
#' ProgressStyle widget
#'
#' @export
jupyter.widget.ProgressStyle <- R6::R6Class("jupyter.widget.ProgressStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param bar_color Color of the progress bar.
    #' @param description_width Width of the description to the side of the control.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ProgressStyle' widget
    initialize = function(
      bar_color = NULL,
      description_width = "",

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        bar_color = self$check_state('bar_color', bar_color),
        description_width = self$check_state('description_width', description_width)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ProgressStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field bar_color
    #' Color of the progress bar.
    bar_color = function(x) if(missing(x)) private$state_[['bar_color']] else self$update(bar_color = self$check_state('bar_color', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x))
  )
)

#' ProgressStyle widget
#'
#' @param bar_color Color of the progress bar.
#' @param description_width Width of the description to the side of the control.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ProgressStyle <- function(
  bar_color = NULL,
  description_width = "",
  ...,
  error_call = current_env()
){
  jupyter.widget.ProgressStyle$new(
    bar_color = bar_color,
    description_width = description_width,
    ...,
    error_call = error_call
  )
}

#' ToggleButtonStyle widget
#'
#' @export
jupyter.widget.ToggleButtonStyle <- R6::R6Class("jupyter.widget.ToggleButtonStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param description_width Width of the description to the side of the control.
    #' @param font_family Toggle button text font family.
    #' @param font_size Toggle button text font size.
    #' @param font_style Toggle button text font style.
    #' @param font_variant Toggle button text font variant.
    #' @param font_weight Toggle button text font weight.
    #' @param text_color Toggle button text color
    #' @param text_decoration Toggle button text decoration.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ToggleButtonStyle' widget
    initialize = function(
      description_width = "",
      font_family = NULL,
      font_size = NULL,
      font_style = NULL,
      font_variant = NULL,
      font_weight = NULL,
      text_color = NULL,
      text_decoration = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        description_width = self$check_state('description_width', description_width),
        font_family = self$check_state('font_family', font_family),
        font_size = self$check_state('font_size', font_size),
        font_style = self$check_state('font_style', font_style),
        font_variant = self$check_state('font_variant', font_variant),
        font_weight = self$check_state('font_weight', font_weight),
        text_color = self$check_state('text_color', text_color),
        text_decoration = self$check_state('text_decoration', text_decoration)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ToggleButtonStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field font_family
    #' Toggle button text font family.
    font_family = function(x) if(missing(x)) private$state_[['font_family']] else self$update(font_family = self$check_state('font_family', x)),
    
    #' @field font_size
    #' Toggle button text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field font_style
    #' Toggle button text font style.
    font_style = function(x) if(missing(x)) private$state_[['font_style']] else self$update(font_style = self$check_state('font_style', x)),
    
    #' @field font_variant
    #' Toggle button text font variant.
    font_variant = function(x) if(missing(x)) private$state_[['font_variant']] else self$update(font_variant = self$check_state('font_variant', x)),
    
    #' @field font_weight
    #' Toggle button text font weight.
    font_weight = function(x) if(missing(x)) private$state_[['font_weight']] else self$update(font_weight = self$check_state('font_weight', x)),
    
    #' @field text_color
    #' Toggle button text color
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x)),
    
    #' @field text_decoration
    #' Toggle button text decoration.
    text_decoration = function(x) if(missing(x)) private$state_[['text_decoration']] else self$update(text_decoration = self$check_state('text_decoration', x))
  )
)

#' ToggleButtonStyle widget
#'
#' @param description_width Width of the description to the side of the control.
#' @param font_family Toggle button text font family.
#' @param font_size Toggle button text font size.
#' @param font_style Toggle button text font style.
#' @param font_variant Toggle button text font variant.
#' @param font_weight Toggle button text font weight.
#' @param text_color Toggle button text color
#' @param text_decoration Toggle button text decoration.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ToggleButtonStyle <- function(
  description_width = "",
  font_family = NULL,
  font_size = NULL,
  font_style = NULL,
  font_variant = NULL,
  font_weight = NULL,
  text_color = NULL,
  text_decoration = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.ToggleButtonStyle$new(
    description_width = description_width,
    font_family = font_family,
    font_size = font_size,
    font_style = font_style,
    font_variant = font_variant,
    font_weight = font_weight,
    text_color = text_color,
    text_decoration = text_decoration,
    ...,
    error_call = error_call
  )
}

rlang::on_load({
  set_widget_state_check("jupyter.widget.ToggleButtonStyle", "font_variant", unbox_one_of(c("normal", "small-caps", "all-small-caps", "petite-caps", "all-petite-caps", "unicase", "titling-caps"), allow_null = TRUE, allow_empty = FALSE))
})
