# Generated by jupyter.widgets.generate::generate_dom_widget("Combobox"): do not edit by hand

#' Combobox widget
#'
#' @export
jupyter.widget.Combobox <- R6::R6Class("jupyter.widget.Combobox", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param continuous_update Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes
    #' @param ensure_option If set, ensure value is in options. Implies continuous_update=False.
    #' @param options Dropdown options for the combobox
    #' @param placeholder Placeholder text to display when nothing has been typed
    #' @param value String value
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.Combobox' widget
    initialize = function(
      continuous_update = TRUE,
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      ensure_option = FALSE,
      options = list(),
      placeholder = "\U{200B}",
      value = "",

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        continuous_update = self$check_state('continuous_update', continuous_update),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        ensure_option = self$check_state('ensure_option', ensure_option),
        options = self$check_state('options', options),
        placeholder = self$check_state('placeholder', placeholder),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ComboboxModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "ComboboxView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field continuous_update
    #' Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
    continuous_update = function(x) if(missing(x)) private$state_[['continuous_update']] else self$update(continuous_update = self$check_state('continuous_update', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field ensure_option
    #' If set, ensure value is in options. Implies continuous_update=False.
    ensure_option = function(x) if(missing(x)) private$state_[['ensure_option']] else self$update(ensure_option = self$check_state('ensure_option', x)),
    
    #' @field options
    #' Dropdown options for the combobox
    options = function(x) if(missing(x)) private$state_[['options']] else self$update(options = self$check_state('options', x)),
    
    #' @field placeholder
    #' Placeholder text to display when nothing has been typed
    placeholder = function(x) if(missing(x)) private$state_[['placeholder']] else self$update(placeholder = self$check_state('placeholder', x)),
    
    #' @field value
    #' String value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' Combobox widget
#'
#' @param continuous_update Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes
#' @param ensure_option If set, ensure value is in options. Implies continuous_update=False.
#' @param options Dropdown options for the combobox
#' @param placeholder Placeholder text to display when nothing has been typed
#' @param value String value
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
Combobox <- function(
  continuous_update = TRUE,
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  ensure_option = FALSE,
  options = list(),
  placeholder = "\U{200B}",
  value = "",
  ...,
  error_call = current_env()
){
  jupyter.widget.Combobox$new(
    continuous_update = continuous_update,
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    ensure_option = ensure_option,
    options = options,
    placeholder = placeholder,
    value = value,
    ...,
    error_call = error_call
  )
}

