# Generated by jupyter.widgets.generate::generate_dom_widget("ColorPicker"): do not edit by hand

#' ColorPicker widget
#'
#' @export
jupyter.widget.ColorPicker <- R6::R6Class("jupyter.widget.ColorPicker", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param concise Display short version with just a color selector.
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes.
    #' @param value The color value.
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.ColorPicker' widget
    initialize = function(
      concise = FALSE,
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      value = "black",

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        concise = self$check_state('concise', concise),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "ColorPickerModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "ColorPickerView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field concise
    #' Display short version with just a color selector.
    concise = function(x) if(missing(x)) private$state_[['concise']] else self$update(concise = self$check_state('concise', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes.
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field value
    #' The color value.
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' ColorPicker widget
#'
#' @param concise Display short version with just a color selector.
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes.
#' @param value The color value.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
ColorPicker <- function(
  concise = FALSE,
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  value = "black",
  ...,
  error_call = current_env()
){
  jupyter.widget.ColorPicker$new(
    concise = concise,
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    value = value,
    ...,
    error_call = error_call
  )
}

