# Generated by jupyter.widgets.generate::generate_style_widget("CheckboxStyle"): do not edit by hand

#' CheckboxStyle widget
#'
#' @export
jupyter.widget.CheckboxStyle <- R6::R6Class("jupyter.widget.CheckboxStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.CheckboxStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "CheckboxStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x))
  )
)

#' CheckboxStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
CheckboxStyle <- function(
  background = NULL,
  description_width = "",
  ...,
  error_call = current_env()
){
  jupyter.widget.CheckboxStyle$new(
    background = background,
    description_width = description_width,
    ...,
    error_call = error_call
  )
}
