# Generated by jupyter.widgets.generate::generate_style_widget("SliderStyle"): do not edit by hand

#' SliderStyle widget
#'
#' @export
jupyter.widget.SliderStyle <- R6::R6Class("jupyter.widget.SliderStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param description_width Width of the description to the side of the control.
    #' @param handle_color Color of the slider handle.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.SliderStyle' widget
    initialize = function(
      description_width = "",
      handle_color = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        description_width = self$check_state('description_width', description_width),
        handle_color = self$check_state('handle_color', handle_color)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "SliderStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field handle_color
    #' Color of the slider handle.
    handle_color = function(x) if(missing(x)) private$state_[['handle_color']] else self$update(handle_color = self$check_state('handle_color', x))
  )
)

#' SliderStyle widget
#'
#' @param description_width Width of the description to the side of the control.
#' @param handle_color Color of the slider handle.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
SliderStyle <- function(
  description_width = "",
  handle_color = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.SliderStyle$new(
    description_width = description_width,
    handle_color = handle_color,
    ...,
    error_call = error_call
  )
}
