# Generated by jupyter.widgets.generate::generate_dom_widget("Box"): do not edit by hand

#' Box widget
#'
#' @export
jupyter.widget.Box <- R6::R6Class("jupyter.widget.Box", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param box_style Use a predefined styling for the box.
    #' @param children List of widget children
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.Box' widget
    initialize = function(
      box_style = "",
      children = list(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        box_style = self$check_state('box_style', box_style),
        children = self$check_state('children', children)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "BoxModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "BoxView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field box_style
    #' Use a predefined styling for the box.
    box_style = function(x) if(missing(x)) private$state_[['box_style']] else self$update(box_style = self$check_state('box_style', x)),
    
    #' @field children
    #' List of widget children
    children = function(x) if(missing(x)) private$state_[['children']] else self$update(children = self$check_state('children', x))
  )
)

#' Box widget
#'
#' @param box_style Use a predefined styling for the box.
#' @param children List of widget children
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
Box <- function(
  box_style = "",
  children = list(),
  ...,
  error_call = current_env()
){
  jupyter.widget.Box$new(
    box_style = box_style,
    children = children,
    ...,
    error_call = error_call
  )
}

rlang::on_load({
  set_widget_state_check("jupyter.widget.Box", "box_style", unbox_one_of(c("success", "info", "warning", "danger"), allow_null = TRUE, allow_empty = TRUE))
})
