# Generated by jupyter.widgets.generate::generate_dom_widget("Tab"): do not edit by hand

#' Tab widget
#'
#' @export
jupyter.widget.Tab <- R6::R6Class("jupyter.widget.Tab", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param box_style Use a predefined styling for the box.
    #' @param children List of widget children
    #' @param selected_index The index of the selected page. This is either an integer selecting a particular sub-widget, or None to have no widgets selected.
    #' @param titles Titles of the pages
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.Tab' widget
    initialize = function(
      box_style = "",
      children = list(),
      selected_index = NULL,
      titles = list(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        box_style = self$check_state('box_style', box_style),
        children = self$check_state('children', children),
        selected_index = self$check_state('selected_index', selected_index),
        titles = self$check_state('titles', titles)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "TabModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "TabView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field box_style
    #' Use a predefined styling for the box.
    box_style = function(x) if(missing(x)) private$state_[['box_style']] else self$update(box_style = self$check_state('box_style', x)),
    
    #' @field children
    #' List of widget children
    children = function(x) if(missing(x)) private$state_[['children']] else self$update(children = self$check_state('children', x)),
    
    #' @field selected_index
    #' The index of the selected page. This is either an integer selecting a particular sub-widget, or None to have no widgets selected.
    selected_index = function(x) if(missing(x)) private$state_[['selected_index']] else self$update(selected_index = self$check_state('selected_index', x)),
    
    #' @field titles
    #' Titles of the pages
    titles = function(x) if(missing(x)) private$state_[['titles']] else self$update(titles = self$check_state('titles', x))
  )
)

#' Tab widget
#'
#' @param box_style Use a predefined styling for the box.
#' @param children List of widget children
#' @param selected_index The index of the selected page. This is either an integer selecting a particular sub-widget, or None to have no widgets selected.
#' @param titles Titles of the pages
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
Tab <- function(
  box_style = "",
  children = list(),
  selected_index = NULL,
  titles = list(),
  ...,
  error_call = current_env()
){
  jupyter.widget.Tab$new(
    box_style = box_style,
    children = children,
    selected_index = selected_index,
    titles = titles,
    ...,
    error_call = error_call
  )
}

rlang::on_load({
  set_widget_state_check("jupyter.widget.Tab", "box_style", unbox_one_of(c("success", "info", "warning", "danger"), allow_null = TRUE, allow_empty = TRUE))
})
