# Generated by jupyter.widgets.generate::generate_dom_widget("Textarea"): do not edit by hand

#' Textarea widget
#'
#' @export
jupyter.widget.Textarea <- R6::R6Class("jupyter.widget.Textarea", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param continuous_update Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes
    #' @param placeholder Placeholder text to display when nothing has been typed
    #' @param rows The number of rows to display.
    #' @param value String value
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.Textarea' widget
    initialize = function(
      continuous_update = TRUE,
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      placeholder = "\U{200B}",
      rows = NULL,
      value = "",

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        continuous_update = self$check_state('continuous_update', continuous_update),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        placeholder = self$check_state('placeholder', placeholder),
        rows = self$check_state('rows', rows),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "TextareaModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "TextareaView",
        
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field continuous_update
    #' Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
    continuous_update = function(x) if(missing(x)) private$state_[['continuous_update']] else self$update(continuous_update = self$check_state('continuous_update', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field placeholder
    #' Placeholder text to display when nothing has been typed
    placeholder = function(x) if(missing(x)) private$state_[['placeholder']] else self$update(placeholder = self$check_state('placeholder', x)),
    
    #' @field rows
    #' The number of rows to display.
    rows = function(x) if(missing(x)) private$state_[['rows']] else self$update(rows = self$check_state('rows', x)),
    
    #' @field value
    #' String value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' Textarea widget
#'
#' @param continuous_update Update the value as the user types. If False, update on submission, e.g., pressing Enter or navigating away.
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes
#' @param placeholder Placeholder text to display when nothing has been typed
#' @param rows The number of rows to display.
#' @param value String value
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
Textarea <- function(
  continuous_update = TRUE,
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  placeholder = "\U{200B}",
  rows = NULL,
  value = "",
  ...,
  error_call = current_env()
){
  jupyter.widget.Textarea$new(
    continuous_update = continuous_update,
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    placeholder = placeholder,
    rows = rows,
    value = value,
    ...,
    error_call = error_call
  )
}
