# Generated by jupyter.widgets.generate::generate_dom_widget("Checkbox"): do not edit by hand

#' Checkbox widget
#'
#' @export
jupyter.widget.Checkbox <- R6::R6Class("jupyter.widget.Checkbox", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes.
    #' @param indent Indent the control to align with other controls with a description.
    #' @param value Bool value
    #' @param style Must inherit from [jupyter.widget.CheckboxStyle].
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.Checkbox' widget
    initialize = function(
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      indent = TRUE,
      value = FALSE,
      style = CheckboxStyle(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        indent = self$check_state('indent', indent),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "CheckboxModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "CheckboxView",
        style = style, 
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes.
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field indent
    #' Indent the control to align with other controls with a description.
    indent = function(x) if(missing(x)) private$state_[['indent']] else self$update(indent = self$check_state('indent', x)),
    
    #' @field value
    #' Bool value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' Checkbox widget
#'
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes.
#' @param indent Indent the control to align with other controls with a description.
#' @param value Bool value
#' 
#' @param style Must inherit from [jupyter.widget.CheckboxStyle].
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
Checkbox <- function(
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  indent = TRUE,
  value = FALSE,
  style = CheckboxStyle(),
  ...,
  error_call = current_env()
){
  jupyter.widget.Checkbox$new(
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    indent = indent,
    value = value,
    style = style,
    ...,
    error_call = error_call
  )
}

