# Generated by jupyter.widgets.generate::generate_style_widget("HTMLStyle"): do not edit by hand

#' HTMLStyle widget
#'
#' @export
jupyter.widget.HTMLStyle <- R6::R6Class("jupyter.widget.HTMLStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #' @param font_size Text font size.
    #' @param text_color Text color
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.HTMLStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",
      font_size = NULL,
      text_color = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width),
        font_size = self$check_state('font_size', font_size),
        text_color = self$check_state('text_color', text_color)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "HTMLStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field font_size
    #' Text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field text_color
    #' Text color
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x))
  )
)

#' HTMLStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' @param font_size Text font size.
#' @param text_color Text color
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
HTMLStyle <- function(
  background = NULL,
  description_width = "",
  font_size = NULL,
  text_color = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.HTMLStyle$new(
    background = background,
    description_width = description_width,
    font_size = font_size,
    text_color = text_color,
    ...,
    error_call = error_call
  )
}
