# Generated by jupyter.widgets.generate::generate_style_widget("LabelStyle"): do not edit by hand

#' LabelStyle widget
#'
#' @export
jupyter.widget.LabelStyle <- R6::R6Class("jupyter.widget.LabelStyle", inherit = jupyter.widget.Style,
  public = list(

    #' @param background Background specifications.
    #' @param description_width Width of the description to the side of the control.
    #' @param font_family Label text font family.
    #' @param font_size Text font size.
    #' @param font_style Label text font style.
    #' @param font_variant Label text font variant.
    #' @param font_weight Label text font weight.
    #' @param text_color Text color
    #' @param text_decoration Label text decoration.
    #'
    #' @param ... See [jupyter.widgets.base::Style]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.LabelStyle' widget
    initialize = function(
      background = NULL,
      description_width = "",
      font_family = NULL,
      font_size = NULL,
      font_style = NULL,
      font_variant = NULL,
      font_weight = NULL,
      text_color = NULL,
      text_decoration = NULL,

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        background = self$check_state('background', background),
        description_width = self$check_state('description_width', description_width),
        font_family = self$check_state('font_family', font_family),
        font_size = self$check_state('font_size', font_size),
        font_style = self$check_state('font_style', font_style),
        font_variant = self$check_state('font_variant', font_variant),
        font_weight = self$check_state('font_weight', font_weight),
        text_color = self$check_state('text_color', text_color),
        text_decoration = self$check_state('text_decoration', text_decoration)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "LabelStyleModel",
        `_view_module`  = "@jupyter-widgets/base",
        `_view_name`    = "StyleView",

        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field background
    #' Background specifications.
    background = function(x) if(missing(x)) private$state_[['background']] else self$update(background = self$check_state('background', x)),
    
    #' @field description_width
    #' Width of the description to the side of the control.
    description_width = function(x) if(missing(x)) private$state_[['description_width']] else self$update(description_width = self$check_state('description_width', x)),
    
    #' @field font_family
    #' Label text font family.
    font_family = function(x) if(missing(x)) private$state_[['font_family']] else self$update(font_family = self$check_state('font_family', x)),
    
    #' @field font_size
    #' Text font size.
    font_size = function(x) if(missing(x)) private$state_[['font_size']] else self$update(font_size = self$check_state('font_size', x)),
    
    #' @field font_style
    #' Label text font style.
    font_style = function(x) if(missing(x)) private$state_[['font_style']] else self$update(font_style = self$check_state('font_style', x)),
    
    #' @field font_variant
    #' Label text font variant.
    font_variant = function(x) if(missing(x)) private$state_[['font_variant']] else self$update(font_variant = self$check_state('font_variant', x)),
    
    #' @field font_weight
    #' Label text font weight.
    font_weight = function(x) if(missing(x)) private$state_[['font_weight']] else self$update(font_weight = self$check_state('font_weight', x)),
    
    #' @field text_color
    #' Text color
    text_color = function(x) if(missing(x)) private$state_[['text_color']] else self$update(text_color = self$check_state('text_color', x)),
    
    #' @field text_decoration
    #' Label text decoration.
    text_decoration = function(x) if(missing(x)) private$state_[['text_decoration']] else self$update(text_decoration = self$check_state('text_decoration', x))
  )
)

#' LabelStyle widget
#'
#' @param background Background specifications.
#' @param description_width Width of the description to the side of the control.
#' @param font_family Label text font family.
#' @param font_size Text font size.
#' @param font_style Label text font style.
#' @param font_variant Label text font variant.
#' @param font_weight Label text font weight.
#' @param text_color Text color
#' @param text_decoration Label text decoration.
#' 
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.Style] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
LabelStyle <- function(
  background = NULL,
  description_width = "",
  font_family = NULL,
  font_size = NULL,
  font_style = NULL,
  font_variant = NULL,
  font_weight = NULL,
  text_color = NULL,
  text_decoration = NULL,
  ...,
  error_call = current_env()
){
  jupyter.widget.LabelStyle$new(
    background = background,
    description_width = description_width,
    font_family = font_family,
    font_size = font_size,
    font_style = font_style,
    font_variant = font_variant,
    font_weight = font_weight,
    text_color = text_color,
    text_decoration = text_decoration,
    ...,
    error_call = error_call
  )
}
