# Generated by jupyter.widgets.generate::generate_dom_widget("HTML"): do not edit by hand

#' HTML widget
#'
#' @export
jupyter.widget.HTML <- R6::R6Class("jupyter.widget.HTML", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param placeholder Placeholder text to display when nothing has been typed
    #' @param value String value
    #' @param style Must inherit from [jupyter.widget.HTMLStyle].
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.HTML' widget
    initialize = function(
      description = "",
      description_allow_html = FALSE,
      placeholder = "\U{200B}",
      value = "",
      style = HTMLStyle(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        placeholder = self$check_state('placeholder', placeholder),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "HTMLModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "HTMLView",
        style = style, 
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field placeholder
    #' Placeholder text to display when nothing has been typed
    placeholder = function(x) if(missing(x)) private$state_[['placeholder']] else self$update(placeholder = self$check_state('placeholder', x)),
    
    #' @field value
    #' String value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' HTML widget
#'
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param placeholder Placeholder text to display when nothing has been typed
#' @param value String value
#' 
#' @param style Must inherit from [jupyter.widget.HTMLStyle].
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
HTML <- function(
  description = "",
  description_allow_html = FALSE,
  placeholder = "\U{200B}",
  value = "",
  style = HTMLStyle(),
  ...,
  error_call = current_env()
){
  jupyter.widget.HTML$new(
    description = description,
    description_allow_html = description_allow_html,
    placeholder = placeholder,
    value = value,
    style = style,
    ...,
    error_call = error_call
  )
}
