# Generated by jupyter.widgets.generate::generate_dom_widget("IntSlider"): do not edit by hand
# rather add a IntSlider.R file that starts with this if you want to add custom code
#
# #' @include IntSlider-generated.R
# NULL

#' IntSlider widget
#'
#' @export
jupyter.widget.IntSlider <- R6::R6Class("jupyter.widget.IntSlider", inherit = jupyter.widget.DOMWidget,
  public = list(

    #' @param behavior Slider dragging behavior.
    #' @param continuous_update Update the value of the widget as the user is holding the slider.
    #' @param description Description of the control.
    #' @param description_allow_html Accept HTML in the description.
    #' @param disabled Enable or disable user changes
    #' @param max Max value
    #' @param min Min value
    #' @param orientation Vertical or horizontal.
    #' @param readout Display the current value of the slider next to it.
    #' @param readout_format Format for the readout
    #' @param step Minimum step to increment the value
    #' @param value Int value
    #' @param style Must inherit from [jupyter.widget.SliderStyle].
    #'
    #' @param ... See [jupyter.widgets.base::DOMWidget]
    #' @param error_call see [rlang::args_error_context()]
    #'
    #' @return a new 'jupyter.widget.IntSlider' widget
    initialize = function(
      behavior = "drag-tap",
      continuous_update = TRUE,
      description = "",
      description_allow_html = FALSE,
      disabled = FALSE,
      max = 100L,
      min = 0L,
      orientation = "horizontal",
      readout = TRUE,
      readout_format = "d",
      step = 1L,
      value = 0L,
      style = SliderStyle(),

      ...,
      error_call = caller_env()
    )
    {
      private$state_ <- update_list(private$state_,
        behavior = self$check_state('behavior', behavior),
        continuous_update = self$check_state('continuous_update', continuous_update),
        description = self$check_state('description', description),
        description_allow_html = self$check_state('description_allow_html', description_allow_html),
        disabled = self$check_state('disabled', disabled),
        max = self$check_state('max', max),
        min = self$check_state('min', min),
        orientation = self$check_state('orientation', orientation),
        readout = self$check_state('readout', readout),
        readout_format = self$check_state('readout_format', readout_format),
        step = self$check_state('step', step),
        value = self$check_state('value', value)
      )

      super$initialize(
        `_model_module` = "@jupyter-widgets/controls",
        `_model_name`   = "IntSliderModel",
        `_view_module`  = "@jupyter-widgets/controls",
        `_view_name`    = "IntSliderView",
        style = style, 
        ...,
        error_call = error_call
      )

    }
  ),

  active = list(
    
    #' @field behavior
    #' Slider dragging behavior.
    behavior = function(x) if(missing(x)) private$state_[['behavior']] else self$update(behavior = self$check_state('behavior', x)),
    
    #' @field continuous_update
    #' Update the value of the widget as the user is holding the slider.
    continuous_update = function(x) if(missing(x)) private$state_[['continuous_update']] else self$update(continuous_update = self$check_state('continuous_update', x)),
    
    #' @field description
    #' Description of the control.
    description = function(x) if(missing(x)) private$state_[['description']] else self$update(description = self$check_state('description', x)),
    
    #' @field description_allow_html
    #' Accept HTML in the description.
    description_allow_html = function(x) if(missing(x)) private$state_[['description_allow_html']] else self$update(description_allow_html = self$check_state('description_allow_html', x)),
    
    #' @field disabled
    #' Enable or disable user changes
    disabled = function(x) if(missing(x)) private$state_[['disabled']] else self$update(disabled = self$check_state('disabled', x)),
    
    #' @field max
    #' Max value
    max = function(x) if(missing(x)) private$state_[['max']] else self$update(max = self$check_state('max', x)),
    
    #' @field min
    #' Min value
    min = function(x) if(missing(x)) private$state_[['min']] else self$update(min = self$check_state('min', x)),
    
    #' @field orientation
    #' Vertical or horizontal.
    orientation = function(x) if(missing(x)) private$state_[['orientation']] else self$update(orientation = self$check_state('orientation', x)),
    
    #' @field readout
    #' Display the current value of the slider next to it.
    readout = function(x) if(missing(x)) private$state_[['readout']] else self$update(readout = self$check_state('readout', x)),
    
    #' @field readout_format
    #' Format for the readout
    readout_format = function(x) if(missing(x)) private$state_[['readout_format']] else self$update(readout_format = self$check_state('readout_format', x)),
    
    #' @field step
    #' Minimum step to increment the value
    step = function(x) if(missing(x)) private$state_[['step']] else self$update(step = self$check_state('step', x)),
    
    #' @field value
    #' Int value
    value = function(x) if(missing(x)) private$state_[['value']] else self$update(value = self$check_state('value', x))
  )
)

#' IntSlider widget
#'
#' @param behavior Slider dragging behavior.
#' @param continuous_update Update the value of the widget as the user is holding the slider.
#' @param description Description of the control.
#' @param description_allow_html Accept HTML in the description.
#' @param disabled Enable or disable user changes
#' @param max Max value
#' @param min Min value
#' @param orientation Vertical or horizontal.
#' @param readout Display the current value of the slider next to it.
#' @param readout_format Format for the readout
#' @param step Minimum step to increment the value
#' @param value Int value
#' 
#' @param style Must inherit from [jupyter.widget.SliderStyle].
#' 
#' @param ... forwarded to [jupyter.widgets.base::jupyter.widget.DOMWidget] constructor
#' @inheritParams rlang::args_error_context
#'
#' @export
IntSlider <- function(
  behavior = "drag-tap",
  continuous_update = TRUE,
  description = "",
  description_allow_html = FALSE,
  disabled = FALSE,
  max = 100L,
  min = 0L,
  orientation = "horizontal",
  readout = TRUE,
  readout_format = "d",
  step = 1L,
  value = 0L,
  style = SliderStyle(),
  ...,
  error_call = current_env()
){
  jupyter.widget.IntSlider$new(
    behavior = behavior,
    continuous_update = continuous_update,
    description = description,
    description_allow_html = description_allow_html,
    disabled = disabled,
    max = max,
    min = min,
    orientation = orientation,
    readout = readout,
    readout_format = readout_format,
    step = step,
    value = value,
    style = style,
    ...,
    error_call = error_call
  )
}
